@tool
class_name QuickExportSettings
extends Node
## Editor helper for configuring existing export presets. [br]
## Add this script to a Node, press the desired buttons, then remove the Node.


#region export paths


@export_group("Export paths")


## Root folder used for every build
@export_global_dir var builds_root: String = _get_default_builds_root()


## Reset the builds root to the current user's Documents/project_name/Builds folder
@export_tool_button("Reset path to Documents/ProjectName/Builds")
var reset_builds_root: Callable = _reset_builds_root


func _get_default_builds_root() -> String:
	# get Documents folder in your pc
	var documents_path: String = OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)
	if documents_path.is_empty():
		return ""
	# and return path/to/Documents/project_name/Builds
	return documents_path.path_join(_get_project_name()).path_join("Builds")


func _reset_builds_root() -> void:
	# reset path to default folder, and update variable in inspector
	builds_root = _get_default_builds_root()
	notify_property_list_changed()
	_success_message(str("Builds root reset to '", builds_root, "'"))


#endregion


#region project settings for export builds


@export_group("Project Settings for export builds")


## Set texture compression for build android
@export_tool_button("Set texture compression for android")
var settings_for_android: Callable = _settings_for_android


const TEXTURE_COMPRESSION_SETTING: String = "rendering/textures/vram_compression/import_etc2_astc"


func _settings_for_android() -> void:
	# update settings for android
	var setting: bool = ProjectSettings.get_setting(TEXTURE_COMPRESSION_SETTING, false)
	if setting == false:
		ProjectSettings.set_setting(TEXTURE_COMPRESSION_SETTING, true)
		_save_project_settings("Edited settings for Android build")
	# if not already set
	else:
		_warning_message("Settings are already ready for Android build")


#endregion


#region configure presets


@export_group("Configure presets")


## Path to the export_presets.cfg generated by godot when add exports to the project
@export_file var export_presets_path: String = "res://export_presets.cfg"


# how are declared presets inside the file
const PRESET_SECTION_PREFIX: String = "preset."		# preset.0, preset.1, etc...
const OPTIONS_SECTION_SUFFIX: String = ".options"	# preset.0.options, preset.1.options, etc...

# possible devices
enum Device {
	NONE = 0,
	ANDROID = 1 << 0,
	LINUX = 1 << 1,
	WINDOWS = 1 << 2,
	WEBGL = 1 << 3,
	ALL = (1 << 4) - 1,
}

func _get_device_name(device: Device) -> String:
	return str(Device.find_key(device))


## Devices affected by the buttons below
@export_flags("Android", "Linux", "Windows", "WebGL")
var selected_devices: int = Device.ALL


## Create the selected device folders without editing export_presets.cfg
@export_tool_button("Create folders")
var create_export_folders: Callable = _create_export_folders


## Set the export build path for the selected devices
@export_tool_button("Set export build path")
var set_export_build_path: Callable = _set_export_build_path


## Set embed PCK for desktop and mobile texture compression for WebGL
@export_tool_button("Set generic settings")
var set_generic_settings: Callable = _set_generic_settings


## Disable immersive mode in the selected Android presets
@export_tool_button("Disable immersive mode Android")
var disable_immersive_mode_android: Callable = _disable_immersive_mode_android


## Run every operation above for the selected devices
@export_tool_button("Do everything")
var do_everything: Callable = _do_everything


# necessary options
const PLATFORM_KEY: String = "platform"
const ANDROID_FORMAT_KEY: String = "gradle_build/export_format"

# options to set
const EXPORT_PATH_KEY: String = "export_path" # for every device
const EMBED_PCK_KEY: String = "binary_format/embed_pck" # for linux and windows
const WEB_MOBILE_COMPRESSION_KEY: String = "vram_texture_compression/for_mobile" # for webgl
const ANDROID_IMMERSIVE_MODE_KEY: String = "screen/immersive_mode" # for android


enum Action {
	NONE = 0,
	CREATE_FOLDERS = 1 << 0, # create folders in computer
	SET_EXPORT_PATH = 1 << 1, # set export path in export_presets for selected devices
	SET_GENERIC_SETTINGS = 1 << 2, # set almost always correct settings (linux and windows embed_pck, texture compression for webgl)
	DISABLE_ANDROID_IMMERSIVE_MODE = 1 << 3, # disable immersive mode for android (e.g. on Jolla phone keyboard doesn't appear when select a LineEdit if immersive mode is enabled)
	ALL = (1 << 4) - 1,
}


func _create_export_folders() -> void:
	_configure_selected_presets(Action.CREATE_FOLDERS)


func _set_export_build_path() -> void:
	_configure_selected_presets(Action.SET_EXPORT_PATH)


func _set_generic_settings() -> void:
	_configure_selected_presets(Action.SET_GENERIC_SETTINGS)


func _disable_immersive_mode_android() -> void:
	# be sure to select android to set its immersive mode
	if (selected_devices & Device.ANDROID) == 0:
		_warning_message("Select Android before disable immersive mode")
		return
	_configure_selected_presets(Action.DISABLE_ANDROID_IMMERSIVE_MODE)


func _do_everything() -> void:
	_configure_selected_presets(Action.ALL)


func _get_selected_devices() -> Array[Device]:
	# from flags, return readable devices
	var devices: Array[Device] = []
	if (selected_devices & Device.ANDROID) != 0:
		devices.append(Device.ANDROID)
	if (selected_devices & Device.LINUX) != 0:
		devices.append(Device.LINUX)
	if (selected_devices & Device.WINDOWS) != 0:
		devices.append(Device.WINDOWS)
	if (selected_devices & Device.WEBGL) != 0:
		devices.append(Device.WEBGL)
	return devices


func _configure_selected_presets(actions: int) -> void:
	# get an array of requested devices (Android, Linux, etc...)
	var requested_devices: Array[Device] = _get_selected_devices()
	if requested_devices.is_empty():
		_warning_message("Select at least one device")
		return

	# create folders
	var folders_created: bool = false
	if (actions & Action.CREATE_FOLDERS) != 0:
		folders_created = _create_folders_for_devices(requested_devices)
		if folders_created:
			_success_message("Export folders created")

	# creating folders does not need to read or edit export_presets.cfg, so can stop here
	if actions == Action.CREATE_FOLDERS:
		if not folders_created:
			_warning_message(_get_no_changes_message(actions))
		return

	# load export_presets.cfg file
	var export_settings: ConfigFile = _load_export_settings()
	if not export_settings:
		return

	var config_changed: bool = false
	var matched_devices: Array[Device] = []
	var preset_index: int = 0

	# cycle every preset (they are named preset.0, preset.1, etc...)
	while true:
		var preset_section: String = PRESET_SECTION_PREFIX + str(preset_index)
		if not export_settings.has_section(preset_section):
			break

		# check if this is a requested device to edit
		var platform: String = str(export_settings.get_value(preset_section, PLATFORM_KEY, ""))
		var device: Device = _get_device_from_platform(platform)
		if requested_devices.has(device):
			if not matched_devices.has(device):
				matched_devices.append(device)

			# and try edit it
			config_changed = _apply_actions_to_preset(export_settings, preset_section, device, actions) or config_changed

		preset_index += 1

	# warning for every device not found
	for device: Device in requested_devices:
		if not matched_devices.has(device):
			_warning_message(str("No ", _get_device_name(device), " export preset found"))

	if config_changed:
		_save_export_settings(export_settings)

	if not config_changed and not folders_created:
		_warning_message(_get_no_changes_message(actions))


func _create_folders_for_devices(devices: Array[Device]) -> bool:
	if builds_root.is_empty():
		_reset_builds_root()

	var folder_created: bool = false

	for device: Device in devices:
		# get "path/to/Documents/project_name/Builds/device/" 
		# where device is Android, Linux, etc...
		var export_directory: String = builds_root.simplify_path().path_join(_get_device_name(device))

		# create folders if not exist
		if DirAccess.dir_exists_absolute(export_directory):
			continue

		var directory_error: Error = DirAccess.make_dir_recursive_absolute(export_directory)
		if directory_error != OK: # and directory_error != ERR_ALREADY_EXISTS:
			_error_message(str("Cannot create '", export_directory, "': "), directory_error)
		else:
			folder_created = true

	return folder_created


# Apply the requested actions to a single preset.
# config is export_presets file, 
# preset_section is preset.0, preset.1, etc...
# device is Android, Linux, etc...
# actions is the list of action to do (set export path, generic settings, etc...)
func _apply_actions_to_preset(config: ConfigFile, preset_section: String, device: Device, actions: int) -> bool:
	# get options (they are named preset.0.options, preset.1.options, etc...)
	var options_section: String = preset_section + OPTIONS_SECTION_SUFFIX

	var config_changed: bool = false

	# set export path
	if (actions & Action.SET_EXPORT_PATH) != 0:
		var export_path: String = _get_export_path(config, options_section, device)
		config_changed = _set_value_if_different(config, preset_section, EXPORT_PATH_KEY, export_path) or config_changed

	# set generic settings
	if (actions & Action.SET_GENERIC_SETTINGS) != 0:
		match device:
			Device.LINUX, Device.WINDOWS:
				config_changed = _set_value_if_different(config, options_section, EMBED_PCK_KEY, true) or config_changed
			Device.WEBGL:
				config_changed = _set_value_if_different(config, options_section, WEB_MOBILE_COMPRESSION_KEY, true) or config_changed

	# disable android immersive mode
	if (actions & Action.DISABLE_ANDROID_IMMERSIVE_MODE) != 0 and device == Device.ANDROID:
		config_changed = _set_value_if_different(config, options_section, ANDROID_IMMERSIVE_MODE_KEY, false) or config_changed

	return config_changed


func _get_no_changes_message(actions: int) -> String:
	match actions:
		Action.CREATE_FOLDERS:
			return "Selected export folders already exist"
		Action.SET_EXPORT_PATH:
			return "Selected export build paths are already configured"
		Action.SET_GENERIC_SETTINGS:
			return "Generic settings are already configured for the selected devices"
		Action.DISABLE_ANDROID_IMMERSIVE_MODE:
			return "Android immersive mode is already disabled"
		_:
			return "Everything is already configured for the selected devices"


func _get_device_from_platform(platform: String) -> Device:
	# from options platform, return readable device
	match platform:
		"Android":
			return Device.ANDROID
		"Linux", "Linux/BSD", "Linux/X11":
			return Device.LINUX
		"Windows", "Windows Desktop":
			return Device.WINDOWS
		"Web", "WebGL", "HTML5":
			return Device.WEBGL
		_:
			return Device.NONE


# return path/to/Documents/project_name/Builds/device/file_name.extension
func _get_export_path(config: ConfigFile, options_section: String, device: Device) -> String:
	# get "path/to/Documents/project_name/Builds/device/" 
	# where device is Android, Linux, etc...
	if builds_root.is_empty():
		_reset_builds_root()
	var export_directory: String = builds_root.simplify_path().path_join(_get_device_name(device))

	var project_name: String = _get_project_name()
	var file_name: String

	# get file_name.extension
	match device:
		Device.ANDROID:
			var android_format: int = int(config.get_value(options_section, ANDROID_FORMAT_KEY, 0))
			file_name = project_name + (".aab" if android_format == 1 else ".apk")
		Device.LINUX:
			file_name = project_name + ".x86_64"
		Device.WINDOWS:
			file_name = project_name + ".exe"
		Device.WEBGL:
			file_name = "index.html"
		_:
			file_name = project_name

	return export_directory.path_join(file_name)


func _set_value_if_different(config: ConfigFile, section: String, key: String, value: Variant) -> bool:
	# ignore if already correct
	if config.has_section_key(section, key) and config.get_value(section, key) == value:
		return false
	# or set it
	config.set_value(section, key, value)
	return true


#endregion


#region Android release keystore


@export_group("Android release keystore")


## Path to the keystore used for android release builds
@export_global_file var android_keystore_path: String = ""


## Set the keystore path to res://ProjectName.keystore
@export_tool_button("Set path to project root")
var set_keystore_to_project_root: Callable = _set_keystore_to_project_root



@export_subgroup("Safe creation")


## For a Safe Creation, create a file .txt with format: [keystore] \n alias="alias_value" \n password="password_value" [br]
## and save it outside the project
@export_global_file var  safe_keystore_credentials_path: String = ""


## Generate safe_keystore_credentials with correct format
@export_tool_button("Generate default file with correct format")
var generate_default_file_with_correct_format: Callable = _generate_default_file_with_correct_format


## Read alias and password from keystore_credentials.txt
@export_tool_button("Create keystore - Safe")
var create_keystore_safe: Callable = _create_keystore_safe


# options inside credentials file
const KEYSTORE_CREDENTIALS_SECTION: String = "keystore"
const KEYSTORE_ALIAS_KEY: String = "alias"
const KEYSTORE_PASSWORD_KEY: String = "password"
 


@export_subgroup("Fast creation")


## Alias used only by Fast creation
@export var fast_keystore_alias: String = ""


## Password used only by Fast creation
@export var fast_keystore_password: String = ""


## After create keystore with Fast Creation, clear alias and password from inspector. [br]
## This is used to avoid push credentials unintentionally
@export var clear_credentials_after_create_keystore: bool = true


## Create the keystore using credentials written in the Inspector
@export_tool_button("Create keystore - Fast")
var create_keystore_fast: Callable = _create_keystore_fast



const START_PROJECT_PATH: String = "res://"

# options inside export settings
const ANDROID_RELEASE_KEYSTORE_PATH_KEY: String = "keystore/release"
const ANDROID_RELEASE_ALIAS_KEY: String = "keystore/release_user"
const ANDROID_RELEASE_PASSWORD_KEY: String = "keystore/release_password"

# generate also export_credentials.cfg
const EXPORT_CREDENTIALS_PATH: String = "res://.godot/export_credentials.cfg"


func _set_keystore_to_project_root() -> void:
	# reset android_keystore_path to project path, and update variable in inspectpr
	var project_name: String = _get_project_name()
	android_keystore_path = START_PROJECT_PATH + project_name + ".keystore"
	notify_property_list_changed()
	_success_message(str("Android keystore path set to '", android_keystore_path, "'"))


func _get_global_path(current_path: String) -> String:
	# trim current path
	current_path = current_path.strip_edges()
	if current_path.is_empty():
		return ""
	# if local to project, return absolute path
	return ProjectSettings.globalize_path(current_path).simplify_path()


## Generate safe_keystore_credentials with correct format
func _generate_default_file_with_correct_format() -> void:
	var credentials_path: String = str(START_PROJECT_PATH, "keystore_credentials.txt")

	# never overwrite an existing credentials file
	if FileAccess.file_exists(credentials_path):
		_warning_message(str("Safe keystore credentials file already exists at '", credentials_path, "'. The existing file has not been overwritten."))
		
		# update variable in inspector
		safe_keystore_credentials_path = credentials_path
		notify_property_list_changed()
		
		return

	# create file with alias "" and password ""
	var credentials := ConfigFile.new()
	credentials.set_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_ALIAS_KEY, "")
	credentials.set_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_PASSWORD_KEY, "")

	# save it
	var save_error: Error = credentials.save(credentials_path)
	if save_error == OK:
		_success_message(str("Safe keystore credentials file created at '", credentials_path, "'"))
		_warn_if_path_is_inside_project(credentials_path, "The credentials file")
		# update variable in inspector
		safe_keystore_credentials_path = credentials_path
		notify_property_list_changed()
	else:
		_error_message("Cannot create Safe keystore credentials file: ", save_error)


## Read alias and password from keystore_credentials.txt
func _create_keystore_safe() -> void:
	# get keystore and credentials path
	var keystore_path: String = _get_global_path(android_keystore_path)
	if keystore_path.is_empty():
		_error_message_only("Android keystore path is empty")
		return

	var credentials_path: String = _get_global_path(safe_keystore_credentials_path)
	if credentials_path.is_empty():
		_error_message_only("Android Safe Keystore Credentials path is empty")
		return

	# try load credentials
	var credentials := ConfigFile.new()
	var load_error: Error = credentials.load(credentials_path)
	if load_error == ERR_FILE_NOT_FOUND:
		_error_message_only(str("No credentials file found at '", credentials_path, "'. 
			Expected format: [keystore] \n alias=\"alias_value\" \n password=\"password_value\""))
		return

	if load_error != OK:
		_error_message("Cannot load credentials file: ", load_error)
		return

	# get alias and password
	var alias: String = str(credentials.get_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_ALIAS_KEY, "")).strip_edges()
	var password: String = str(credentials.get_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_PASSWORD_KEY, ""))

	if alias.is_empty() or password.is_empty():
		_error_message_only("The credentials file must contain a valid alias and password")
		return

	# generate keystore and configure export_credentials to use it
	if _generate_android_keystore(keystore_path, alias, password):
		_configure_android_release_credentials(keystore_path, alias, password)

		# warn if keystore or credentials are inside project folder
		_warn_if_path_is_inside_project(keystore_path, "The release keystore")
		_warn_if_path_is_inside_project(credentials_path, "The credentials file")


## Create the keystore using credentials written in the Inspector
func _create_keystore_fast() -> void:
	_warning_message(
		"Fast creation should only be used for debug or testing. 
		Alias and password entered in the Inspector could be saved inside the scene and pushed to the repository. 
		Use 'Create keystore - Safe' for a real release keystore."
	)

	# get keystore
	var keystore_path: String = _get_global_path(android_keystore_path)
	if keystore_path.is_empty():
		_error_message_only("Android keystore path is empty")
		return

	# get alias and password from variables in inspector
	var alias: String = fast_keystore_alias.strip_edges()
	var password: String = fast_keystore_password

	if alias.is_empty() or password.is_empty():
		_error_message_only("Fast keystore alias or password are empty")
		return

	# generate keystore and configure export_credentials to use it
	if _generate_android_keystore(keystore_path, alias, password):
		_configure_android_release_credentials(keystore_path, alias, password)

		# warn if keystore is inside project folder
		_warn_if_path_is_inside_project(keystore_path, "The release keystore")

		# remove credentials from the inspector
		if clear_credentials_after_create_keystore:
			fast_keystore_alias = ""
			fast_keystore_password = ""
			notify_property_list_changed()


## Execute [br]
## keytool -v -genkey -keystore mygame.keystore -alias mygame -keyalg RSA -validity 10000 [br]
## https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html
func _generate_android_keystore(keystore_path: String, alias: String, password: String) -> bool:
	if password.length() < 6:
		_error_message_only("The keystore password must contain at least 6 characters")
		return false

	if FileAccess.file_exists(keystore_path):
		_error_message_only(str("A file already exists at '", keystore_path,"'. It will not be overwritten."))
		return false

	# create directories
	var keystore_directory: String = keystore_path.get_base_dir()
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(keystore_directory)

	if directory_error != OK and directory_error != ERR_ALREADY_EXISTS:
		_error_message("Cannot create keystore keystore_directory: ", directory_error)
		return false

	# execute application to generate keystore
	var keytool_path: String = _get_keytool_path()
	var output: Array = []

	var arguments := PackedStringArray([
		"-v",
		"-genkey",
		"-keystore", keystore_path,
		"-alias", alias,
		"-keyalg", "RSA",
		# "-keysize", "2048",
		"-validity", "10000",
		# next arguments are used to set password, name, organizations, etc... without ask questions in console
		"-storepass", password,
		"-keypass", password,
		"-dname", "CN=Godot Release, O=Godot",
	])

	var exit_code: int = OS.execute(keytool_path, arguments, output, true)

	# check errors
	if exit_code != 0:
		_error_message_only(str("Cannot generate Android keystore. Exit code: ", exit_code, ". Output: ", "\n".join(output)))
		return false

	if not FileAccess.file_exists(keystore_path):
		_error_message_only("Keytool completed but the keystore was not generated")
		return false

	# else, success
	_success_message(str("Android release keystore generated at '", keystore_path, "'"))
	return true


## Find keytool -> java_sdk_folder/bin/keytool
func _get_keytool_path() -> String:
	var executable_name: String = ("keytool.exe" if OS.get_name() == "Windows" else "keytool")
	var java_sdk_path: String = str(EditorInterface.get_editor_settings().get_setting("export/android/java_sdk_path"))

	if not java_sdk_path.is_empty():
		# find keytool -> java_sdk_folder/bin/keytool
		var configured_path: String = java_sdk_path.path_join("bin").path_join(executable_name)

		if FileAccess.file_exists(configured_path):
			return configured_path

	# Fall back to the keytool available in PATH
	return executable_name


func _configure_android_release_credentials(keystore_path: String, alias: String, password: String) -> void:
	# load export_presets.cfg file. 
	# Used only to discover which presets are Android presets
	var export_settings: ConfigFile = _load_export_settings()
	if not export_settings:
		return
	
	# Load Godot's existing credentials to avoid overwriting credentials belonging to other presets
	var export_credentials_config := ConfigFile.new()
	var credentials_error: Error = export_credentials_config.load(EXPORT_CREDENTIALS_PATH)

	if (credentials_error != OK and credentials_error != ERR_FILE_NOT_FOUND):
		_error_message("Cannot load export credentials: ", credentials_error)
		return

	var android_presets_found: int = 0
	var preset_index: int = 0

	# cycle every preset (they are named preset.0, preset.1, etc...)
	while true:
		var preset_section: String = PRESET_SECTION_PREFIX + str(preset_index)
		if not export_settings.has_section(preset_section):
			break		

		# check if this is an Android device to edit
		var platform: String = str(export_settings.get_value(preset_section, PLATFORM_KEY, ""))
		var device: Device = _get_device_from_platform(platform)
		if device == Device.ANDROID:

			# get options (they are named preset.0.options, preset.1.options, etc...)
			var options_section: String = preset_section + OPTIONS_SECTION_SUFFIX

			# set keystore, alias and password, inside export_credentials, by using found options_section
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_KEYSTORE_PATH_KEY, keystore_path)
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_ALIAS_KEY, alias)
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_PASSWORD_KEY, password)

			android_presets_found += 1

		preset_index += 1

	if android_presets_found == 0:
		_warning_message("Keystore generated, but no Android export preset was found")
		return
	
	# now instead of save export_presets.cfg, we must generate a export_credentials.cfg

	# save export_credentials
	var credentials_directory: String = ProjectSettings.globalize_path(EXPORT_CREDENTIALS_PATH.get_base_dir())
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(credentials_directory)
	if (directory_error != OK and directory_error != ERR_ALREADY_EXISTS):
		_error_message("Cannot create export credentials directory: ", directory_error)
		return
	
	_save_export_credentials(export_credentials_config, android_presets_found)


func _warn_if_path_is_inside_project(path: String, description: String) -> void:
	# check if path is inside project
	var global_path: String = ProjectSettings.globalize_path(path)
	var localized_path: String = ProjectSettings.localize_path(global_path)

	# if inside project, show a warning message
	if localized_path.begins_with(START_PROJECT_PATH):
		_warning_message(str(description, " is inside the project. Do not push it to the repository. Add it to .gitignore or, preferably, keep it outside the project."))


#endregion


func _get_project_name() -> String:
	# get project name (if some chars are invalid, they are replaced with underscore _)
	var project_name: String = str(ProjectSettings.get_setting("application/config/name", "GodotProject"))
	project_name = project_name.strip_edges().validate_filename()
	if project_name.is_empty():
		project_name = "GodotProject"
	return project_name


func _save_project_settings(success_message: String) -> void:
	var save_error: Error = ProjectSettings.save()
	if save_error == OK:
		_success_message(success_message)
		push_warning("Project Settings saved! Reload the project to avoid cache bugs")
	else:
		_error_message("Cannot save Project Settings: ", save_error)


func _load_export_settings() -> ConfigFile:
	# load export_presets.cfg file
	var config := ConfigFile.new()
	var load_error: Error = config.load(export_presets_path)

	if load_error == ERR_FILE_NOT_FOUND:
		_error_message_only("No export_presets.cfg found. Create the export presets first. 
			In the top bar: Project > Export > Add > select device. 
			If necessary: Editor > Manage export models > download necessary models. 
			What I download: Windows x86_64 (no console), Linux x86_64, Android (no source), Web no threads. Both debug and release")
		return null

	if load_error != OK:
		_error_message("Cannot load export_presets.cfg: ", load_error)
		return null

	return config


func _save_export_settings(config: ConfigFile) -> void:
	var save_error: Error = config.save(export_presets_path)
	if save_error == OK:
		_success_message("Export presets configured")
		push_warning("Export presets saved! Reload the project so the Export window refreshes its cached presets")
	else:
		_error_message("Cannot save export_presets.cfg: ", save_error)


func _save_export_credentials(config: ConfigFile, android_presets_found: int) -> void:
	var save_error: Error = config.save(EXPORT_CREDENTIALS_PATH)
	if save_error == OK:
		_success_message(str("Android release credentials configured for ", android_presets_found, " preset(s)"))
		push_warning("Export credentials saved! Reload the project so the Export "+ "window refreshes its cached values")
	else:
		_error_message("Cannot save Android export credentials: ", save_error)



func _success_message(message: String) -> void:
	print("Quick Export Settings SUCCESS: ", message)


func _warning_message(message: String) -> void:
	push_warning("Quick Export Settings WARNING: ", message)


func _error_message(message: String, error: Error) -> void:
	push_error("Quick Export Settings ERROR: ", message, error_string(error))


func _error_message_only(message: String) -> void:
	push_error("Quick Export Settings ERROR: ", message)
